# Generated by Django 6.0.5 on 2026-05-31 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('specialties', '0003_alter_diseasecategory_description_doctorprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='تاریخ نوبت')),
                ('appointment_time', models.TimeField(verbose_name='ساعت نوبت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید پزشک'), ('confirmed', 'تایید شده'), ('completed', 'انجام شده'), ('cancelled_by_patient', 'لغو شده توسط بیمار'), ('cancelled_by_doctor', 'لغو شده توسط پزشک'), ('no_show', 'حضور نیافته (بیمار)')], default='pending', max_length=25, verbose_name='وضعیت')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='دلیل کنسلی')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='علائم بیماری')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='specialties.doctorprofile')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-appointment_date', 'appointment_time'],
                'unique_together': {('doctor', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
