# Generated by Django 6.0.5 on 2026-05-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کلینیک')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='محله')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن کلینیک')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.URLField(blank=True, null=True, verbose_name='عکس کلینیک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کلینیک',
                'verbose_name_plural': 'کلینیک\u200cها',
                'ordering': ['name'],
            },
        ),
    ]
