# Generated by Django 6.0.5 on 2026-05-30 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام بیماری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='specialties.specialty')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی بیماری',
                'verbose_name_plural': 'دسته\u200cبندی بیماری\u200cها',
                'ordering': ['name'],
            },
        ),
    ]
