# Generated by Django 6.0.5 on 2026-05-30 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('specialties', '0002_diseasecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه ویزیت')),
                ('gender', models.CharField(choices=[('male', 'آقا'), ('female', 'خانم')], max_length=10, verbose_name='جنسیت')),
                ('visit_type', models.CharField(choices=[('in_person', 'حضوری'), ('online', 'آنلاین'), ('both', 'هر دو')], default='both', max_length=10, verbose_name='نوع ویزیت')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سال سابقه')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='شماره نظام پزشکی')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='clinics.clinic')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='specialties.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
            },
        ),
    ]
